CREATE TABLE IF NOT EXISTS users (
  firebase_uid varchar PRIMARY KEY,
  username varchar UNIQUE NOT NULL,
  elo_rating int DEFAULT 1200
);

CREATE TABLE IF NOT EXISTS standard_questions (
  id SERIAL PRIMARY KEY,
  initials varchar NOT NULL,
  question_text text NOT NULL UNIQUE,
  correct_answer varchar NOT NULL,
  category varchar,
  difficulty int DEFAULT 1
);

CREATE TABLE IF NOT EXISTS yes_no_questions (
  id SERIAL PRIMARY KEY,
  question_text text NOT NULL UNIQUE,
  correct_answer boolean NOT NULL,
  category varchar
);

CREATE TABLE IF NOT EXISTS matches (
  id BIGSERIAL PRIMARY KEY,
  player1_id varchar NOT NULL REFERENCES users (firebase_uid),
  player2_id varchar NOT NULL REFERENCES users (firebase_uid),
  winner_id varchar REFERENCES users (firebase_uid),
  player1_elo_change int,
  player2_elo_change int,
  status varchar NOT NULL DEFAULT 'ongoing' CHECK (status IN ('ongoing', 'completed', 'aborted')),
  started_at timestamp DEFAULT (now()),
  finished_at timestamp
);

CREATE TABLE IF NOT EXISTS match_turns (
  id BIGSERIAL PRIMARY KEY,
  match_id bigint NOT NULL REFERENCES matches (id),
  player_id varchar NOT NULL REFERENCES users (firebase_uid),
  tile_id int NOT NULL,
  standard_question_id int REFERENCES standard_questions (id),
  yes_no_question_id int REFERENCES yes_no_questions (id),
  is_correct boolean NOT NULL,
  turn_timestamp timestamp DEFAULT (now()),
  CONSTRAINT check_one_question_type CHECK (
    (standard_question_id IS NOT NULL AND yes_no_question_id IS NULL)
    OR
    (standard_question_id IS NULL AND yes_no_question_id IS NOT NULL)
  )
);

COMMENT ON COLUMN users.elo_rating IS 'Determines MMR and Leaderboard rank';
COMMENT ON COLUMN standard_questions.initials IS 'e.g., "A", "CH", "K"';
COMMENT ON COLUMN standard_questions.difficulty IS '1 to 5 scale';
COMMENT ON COLUMN yes_no_questions.question_text IS 'For wrongly answered/contested tiles';
COMMENT ON COLUMN matches.winner_id IS 'Null if match is a draw or ongoing';
COMMENT ON COLUMN matches.player1_elo_change IS 'e.g., +15 or -12';
COMMENT ON COLUMN matches.player2_elo_change IS 'e.g., -15 or +12';
COMMENT ON COLUMN matches.status IS 'ongoing, completed, aborted';
COMMENT ON COLUMN match_turns.tile_id IS 'Tile number 1-28 on the AZ kvíz pyramid';
COMMENT ON COLUMN match_turns.standard_question_id IS 'Null if a Yes/No question was used';
COMMENT ON COLUMN match_turns.yes_no_question_id IS 'Null if a standard question was used';

INSERT INTO standard_questions (initials, question_text, correct_answer, category, difficulty) VALUES
('ME', 'What is the tallest mountain on Earth?', 'Mount Everest', 'Geography', 1),
('M', 'What is the closest planet to the Sun?', 'Mercury', 'Science', 1),
('AE', 'Who developed the theory of relativity?', 'Albert Einstein', 'Science', 2),
('H', 'What is the most abundant element in the universe?', 'Hydrogen', 'Science', 2),
('D', 'What molecule carries genetic information?', 'DNA', 'Science', 1),
('D', 'What is the hardest natural substance on Earth?', 'Diamond', 'Science', 1),
('N', 'What do bees collect to make honey?', 'Nectar', 'Science', 1),
('NA', 'Who was the first person to walk on the moon?', 'Neil Armstrong', 'Science', 1),
('IN', 'Who is credited with discovering gravity?', 'Isaac Newton', 'Science', 1),
('O', 'What gas do humans need to breathe to survive?', 'Oxygen', 'Science', 1),
('T', 'What are baby frogs called?', 'Tadpoles', 'Science', 1),
('P', 'What process do plants use to make food?', 'Photosynthesis', 'Science', 2),
('V', 'What is the only planet that rotates clockwise?', 'Venus', 'Science', 3),
('TE', 'Which inventor is known for the light bulb?', 'Thomas Edison', 'Science', 1),
('N', 'What is the center of an atom called?', 'Nucleus', 'Science', 2),
('L', 'What is the fastest speed in the universe?', 'Light', 'Science', 2),
('J', 'What is the largest planet in our solar system?', 'Jupiter', 'Science', 1),
('C', 'Which animal is known for its hump?', 'Camel', 'Science', 1),
('CD', 'Who wrote "The Origin of Species"?', 'Charles Darwin', 'Science', 2),
('BW', 'What is the largest mammal in the world?', 'Blue Whale', 'Science', 1),
('AA', 'What is the building block of proteins?', 'Amino Acids', 'Science', 3),
('G', 'What force keeps us on the ground?', 'Gravity', 'Science', 1),
('A', 'What is the smallest unit of matter?', 'Atom', 'Science', 2),
('MC', 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Science', 2),
('S', 'What is the main source of energy for Earth?', 'Sun', 'Science', 1),
('O', 'What is an eight-sided shape called?', 'Octagon', 'Science', 1),
('B', 'What type of animal is a penguin?', 'Bird', 'Science', 1),
('H', 'Which organ is responsible for pumping blood?', 'Heart', 'Science', 1),
('GW', 'Who was the first President of the United States?', 'George Washington', 'History', 1),
('AL', 'Who issued the Emancipation Proclamation?', 'Abraham Lincoln', 'History', 1),
('T', 'What was the name of the "unsinkable" ship that sank in 1912?', 'Titanic', 'History', 1),
('NM', 'Who was the first Black president of South Africa?', 'Nelson Mandela', 'History', 1),
('RE', 'Which empire was ruled by Julius Caesar?', 'Roman Empire', 'History', 1),
('FR', 'What event began with the storming of the Bastille?', 'French Revolution', 'History', 2),
('AH', 'Who was the leader of Nazi Germany?', 'Adolf Hitler', 'History', 1),
('CC', 'Who reached the Americas in 1492?', 'Christopher Columbus', 'History', 1),
('H', 'What was the ancient Egyptian writing system?', 'Hieroglyphics', 'History', 2),
('W', 'Which battle ended Napoleon’s reign?', 'Waterloo', 'History', 2),
('KA', 'Who was the legendary King of Camelot?', 'King Arthur', 'History', 2),
('WB', 'Who were the brothers who flew the first airplane?', 'Wright Brothers', 'History', 1),
('MT', 'Who was the "Iron Lady" of British politics?', 'Margaret Thatcher', 'History', 2),
('AG', 'Which civilization built the Parthenon?', 'Ancient Greeks', 'History', 2),
('AE', 'Who was the first female pilot to fly solo across the Atlantic?', 'Amelia Earhart', 'History', 2),
('MG', 'Who led the Salt March in India?', 'Mahatma Gandhi', 'History', 2),
('TJ', 'Who was the primary author of the Declaration of Independence?', 'Thomas Jefferson', 'History', 2),
('V', 'Which Norse explorers reached North America before Columbus?', 'Vikings', 'History', 2),
('MP', 'What was the code name for the atomic bomb project?', 'Manhattan Project', 'History', 3),
('BW', 'Which wall fell in 1989?', 'Berlin Wall', 'History', 1),
('PR', 'Who made a famous midnight ride in 1775?', 'Paul Revere', 'History', 2),
('BD', 'What was the nickname for the plague in the 14th century?', 'Black Death', 'History', 2),
('TM', 'Which structure was built as a tomb for a Mughal queen?', 'Taj Mahal', 'History', 2),
('Z', 'What was the name of the Greek king of the gods?', 'Zeus', 'History', 2),
('YG', 'Who was the first human in space?', 'Yuri Gagarin', 'History', 2),
('T', 'What was the main weapon used in medieval sieges?', 'Trebuchet', 'History', 3),
('WS', 'Who wrote "Romeo and Juliet"?', 'William Shakespeare', 'Literature', 1),
('SH', 'Who is the detective living at 221B Baker Street?', 'Sherlock Holmes', 'Literature', 1),
('CA', 'Who is the captain of the Pequod in "Moby Dick"?', 'Captain Ahab', 'Literature', 2),
('G', 'What is the name of the ring-obsessed creature in "Lord of the Rings"?', 'Gollum', 'Literature', 1),
('JG', 'Who is the protagonist of "The Great Gatsby"?', 'Jay Gatsby', 'Literature', 2),
('H', 'Who wrote "The Iliad"?', 'Homer', 'Literature', 2),
('F', 'What was the monster’s name in Mary Shelley’s novel?', 'Frankenstein', 'Literature', 1),
('CD', 'Who wrote "A Tale of Two Cities"?', 'Charles Dickens', 'Literature', 2),('YM', 'What is the setting of "Wuthering Heights"?', 'Yorkshire Moors', 'Literature', 3),
('H', 'What is the name of the protagonist in "The Catcher in the Rye"?', 'Holden Caulfield', 'Literature', 2),
('GO', 'Who wrote the dystopian novel "1984"?', 'George Orwell', 'Literature', 1),
('G', 'Who is the wizard in "The Hobbit"?', 'Gandalf', 'Literature', 1),
('A', 'Who followed the White Rabbit to Wonderland?', 'Alice', 'Literature', 1),
('T', 'Who is the main character in "The Adventures of Tom Sawyer"?', 'Tom Sawyer', 'Literature', 1),
('V', 'Who wrote "Les Misérables"?', 'Victor Hugo', 'Literature', 2),
('MD', 'What is the name of the whale in Herman Melville’s classic?', 'Moby Dick', 'Literature', 1),
('MJ', 'Who is known as the "King of Pop"?', 'Michael Jackson', 'Pop Culture', 1),
('EP', 'Who was the "King of Rock and Roll"?', 'Elvis Presley', 'Pop Culture', 1),
('TB', 'Which band released the album "Abbey Road"?', 'The Beatles', 'Pop Culture', 1),
('SW', 'In which movie is the phrase "May the Force be with you"?', 'Star Wars', 'Pop Culture', 1),
('KE', 'Who is the female lead in "The Hunger Games"?', 'Katniss Everdeen', 'Pop Culture', 1),
('H', 'What is the name of the fictional town in "Stranger Things"?', 'Hawkins', 'Pop Culture', 2),
('TS', 'Who is the singer of "Shake It Off"?', 'Taylor Swift', 'Pop Culture', 1),
('B', 'Who is the caped crusader of Gotham City?', 'Batman', 'Pop Culture', 1),
('LK', 'Which movie features a character named Simba?', 'Lion King', 'Pop Culture', 1),
('S', 'What is the name of the yellow sponge living in a pineapple?', 'SpongeBob', 'Pop Culture', 1),
('JS', 'Who is the main character in the "Pirates of the Caribbean" series?', 'Jack Sparrow', 'Pop Culture', 1),
('MM', 'What is the real name of the rapper Eminem?', 'Marshall Mathers', 'Pop Culture', 2),
('HL', 'Who played the Joker in "The Dark Knight"?', 'Heath Ledger', 'Pop Culture', 2),
('DV', 'Which artist painted the "Mona Lisa"?', 'Da Vinci', 'Art', 1),
('VG', 'Who painted "The Starry Night"?', 'Van Gogh', 'Art', 1),
('PP', 'Which Spanish artist is known for Cubism?', 'Pablo Picasso', 'Art', 2),
('M', 'Who sculpted the statue of David?', 'Michelangelo', 'Art', 2),
('AW', 'Who is the famous pop artist known for Campbell’s Soup cans?', 'Andy Warhol', 'Art', 2),
('FK', 'Which Mexican artist is famous for her self-portraits?', 'Frida Kahlo', 'Art', 2),
('SD', 'Who painted "The Persistence of Memory" (melting clocks)?', 'Salvador Dali', 'Art', 2),
('PP', 'What is the name of the prize given for excellence in journalism?', 'Pulitzer Prize', 'General', 2),
('TS', 'What is the largest organ of the human body?', 'The Skin', 'Science', 2),
('C', 'What is the primary ingredient in hummus?', 'Chickpeas', 'Food', 1),
('S', 'What is the national dish of Japan?', 'Sushi', 'Food', 1),
('T', 'What is the most popular drink in the world after water?', 'Tea', 'Food', 1),
('R', 'What is the capital of Italy?', 'Rome', 'Geography', 1),
('P', 'What is the capital of France?', 'Paris', 'Geography', 1),
('A', 'What is the smallest continent?', 'Australia', 'Geography', 1),
('S', 'What is the name of the fictional city where "The Simpsons" live?', 'Springfield', 'Pop Culture', 1),
('G', 'What does the "G" stand for in FBI?', 'Government', 'General', 2),
('GL', 'Who is the creator of "Star Wars"?', 'George Lucas', 'Pop Culture', 2),
('A', 'Which country is the home of the kangaroo?', 'Australia', 'Geography', 1),
('L', 'What is the Roman numeral for 50?', 'L', 'General', 2),
('D', 'Who is the Greek god of wine?', 'Dionysus', 'History', 2),
('B', 'What is the tallest grass in the world?', 'Bamboo', 'Science', 2),
('S', 'What is the capital of South Korea?', 'Seoul', 'Geography', 2),
('P', 'What is the currency used in the United Kingdom?', 'Pound Sterling', 'General', 1),
('MC', 'Who was the first woman to win a Nobel Prize in two fields?', 'Marie Curie', 'Science', 2),
('PO', 'Which ocean is the largest?', 'Pacific Ocean', 'Geography', 1),
('F', 'Which country gifted the Statue of Liberty to the USA?', 'France', 'History', 1),
('AS', 'Who wrote "The Wealth of Nations"?', 'Adam Smith', 'Literature', 3),
('CB', 'What is the main ingredient of chocolate?', 'Cocoa Beans', 'Food', 1),
('C', 'What is the fastest land animal?', 'Cheetah', 'Science', 1),
('B', 'What is the capital of China?', 'Beijing', 'Geography', 1),
('G', 'What is the study of the Earth’s physical features?', 'Geography', 'Science', 1),
('KM', 'Who wrote "The Communist Manifesto"?', 'Karl Marx', 'History', 2),
('M', 'Which planet is known as the "Red Planet"?', 'Mars', 'Science', 1),
('T', 'What is the capital of Japan?', 'Tokyo', 'Geography', 1),
('S', 'What is the name of the first artificial satellite?', 'Sputnik', 'Science', 2),
('O', 'Which element has the symbol "O"?', 'Oxygen', 'Science', 1),
('Y', 'What is the currency of Japan?', 'Yen', 'General', 1),
('G', 'What is the tallest animal in the world?', 'Giraffe', 'Science', 1),
('EH', 'Who is the author of "The Old Man and the Sea"?', 'Ernest Hemingway', 'Literature', 2),
('O', 'What is the capital of Canada?', 'Ottawa', 'Geography', 2),
('O', 'What is the largest bird in the world?', 'Ostrich', 'Science', 2),
('WS', 'Who is the author of "Hamlet"?', 'William Shakespeare', 'Literature', 1),
('M', 'What is the capital of Spain?', 'Madrid', 'Geography', 1),
('VC', 'What is the smallest country in the world?', 'Vatican City', 'Geography', 2),
('M', 'What is the capital of Russia?', 'Moscow', 'Geography', 1),
('B', 'What is the capital of Germany?', 'Berlin', 'Geography', 1),
('D', 'What is the capital of Ireland?', 'Dublin', 'Geography', 2),
('L', 'What is the capital of the United Kingdom?', 'London', 'Geography', 1)
ON CONFLICT (question_text) DO NOTHING;

INSERT INTO yes_no_questions (question_text, correct_answer, category) VALUES
('Is the sun a star?', true, 'Science'),
('Is the Great Wall of China visible from the moon with the naked eye?', false, 'General'),
('Does water boil at 100 degrees Celsius?', true, 'Science'),
('Is shark a mammal?', false, 'Nature'),
('Is the capital of the USA New York City?', false, 'Geography'),
('Is Mount Kilimanjaro the tallest mountain in the world?', false, 'Geography'),
('Do penguins live in the Arctic?', false, 'Nature'),
('Is the hummingbird the smallest bird?', true, 'Nature'),
('Is gold a liquid at room temperature?', false, 'Science'),
('Is the human body composed of about 60% water?', true, 'Science'),
('Is an octagon a shape with eight sides?', true, 'Math'),
('Is light faster than sound?', true, 'Science'),
('Is the Amazon River the longest river in the world?', false, 'Geography'),
('Is the earth flat?', false, 'Science'),
('Is the moon a planet?', false, 'Science'),
('Is the Atlantic Ocean the largest ocean?', false, 'Geography'),
('Is a tomato a fruit?', true, 'Nature'),
('Is iron a metal?', true, 'Science'),
('Is the Sahara Desert located in Asia?', false, 'Geography'),
('Is French the official language of Brazil?', false, 'General'),
('Is the Venus Flytrap a carnivorous plant?', true, 'Nature'),
('Is Mars closer to the sun than Earth?', false, 'Science'),
('Is the capital of Australia Sydney?', false, 'Geography'),
('Is a spider an insect?', false, 'Nature'),
('Is the Great Barrier Reef located in Australia?', true, 'Geography'),
('Is an island surrounded by water?', true, 'Geography'),
('Is the Pacific Ocean the smallest ocean?', false, 'Geography'),
('Is the cheetah the fastest land animal?', true, 'Nature'),
('Is the eiffel tower in London?', false, 'Geography'),
('Is the pine tree an evergreen?', true, 'Nature'),
('Is the currency of the UK the Euro?', false, 'Finance'),
('Is Tokyo the capital of Japan?', true, 'Geography'),
('Is a leap year 366 days long?', true, 'General'),
('Is the blue whale a fish?', false, 'Nature'),
('Is honey made by bees?', true, 'Nature'),
('Is the human heart a muscle?', true, 'Science'),
('Is the capital of Canada Toronto?', false, 'Geography'),
('Is the Nile River in Africa?', true, 'Geography'),
('Is Pluto considered a planet today?', false, 'Science'),
('Is diamond made of carbon?', true, 'Science'),
('Is the Statue of Liberty in Washington D.C.?', false, 'Geography'),
('Is a square a type of rectangle?', true, 'Math'),
('Is 11 a prime number?', true, 'Math'),
('Is the ostrich the largest bird?', true, 'Nature'),
('Is the North Pole on a continent?', false, 'Geography'),
('Is the Pacific Ocean located between Asia and America?', true, 'Geography'),
('Is a marathon 26.2 miles long?', true, 'Sports'),
('Is the electric light bulb invented by Thomas Edison?', true, 'History'),
('Is the capital of Russia Saint Petersburg?', false, 'Geography'),
('Is the human skeleton made of bones?', true, 'Science'),
('Is zero an even number?', true, 'Math'),
('Is 100 a perfect square?', true, 'Math'),
('Is pi exactly equal to 3?', false, 'Math'),
('Is 29 a prime number?', true, 'Math'),
('Is the square root of 81 equal to 9?', true, 'Math'),
('Is Antarctica the driest continent?', true, 'Geography'),
('Is Iceland part of Europe?', true, 'Geography'),
('Is the Dead Sea below sea level?', true, 'Geography'),
('Is the Danube River in South America?', false, 'Geography'),
('Is Nairobi the capital of Kenya?', true, 'Geography'),
('Is the Sahara Desert the coldest desert on Earth?', false, 'Geography'),
('Is Saturn known for its prominent rings?', true, 'Science'),
('Is lightning hotter than the surface of the sun?', true, 'Science'),
('Is carbon dioxide the most abundant gas in Earth''s atmosphere?', false, 'Science'),
('Is DNA found in most living organisms?', true, 'Science'),
('Is sound able to travel through a vacuum?', false, 'Science'),
('Is Jupiter smaller than Earth?', false, 'Science'),
('Did World War I begin in 1914?', true, 'History'),
('Was Julius Caesar a Roman emperor?', false, 'History'),
('Did the Berlin Wall fall in 1989?', true, 'History'),
('Was Cleopatra the queen of ancient Egypt?', true, 'History'),
('Was the Magna Carta signed in 1215?', true, 'History'),
('Was Leonardo da Vinci born in Spain?', false, 'History'),
('Is "Pride and Prejudice" a novel by Jane Austen?', true, 'Literature')
ON CONFLICT (question_text) DO NOTHING;