name: Prototype Gate               # Název v záložce "Actions" na GitHubu 
permissions:
  contents: write                   # allow the deploy step to push to gh-pages
on:                                 # Kdy se to má spustit?
  pull_request:
    paths:
      - 'prototype/**'              # Jen když někdo upraví soubory ve složce /prototype
    branches: [ main ]             # Jen když někdo chce mergovat do main


env:
  CI: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automaticky vytvoří tajný token pro každé repo, který umožňuje workflow komunikovat s GitHub API (např. pro nasazení na GitHub Pages)
jobs:						        # Joby se pouští paralelně
  test-and-lint-prototype:		    # ID jobu (testy kódu ve folderu /prototype)
    runs-on: ubuntu-latest  		# "Půjč mi od GitHubu čisté Ubuntu"
    steps:					        # Stepy v rámci jobu běží sekvenčně
      - name: Checkout code 		# 1: Stáhni kód z repo do toho Ubuntu
        uses: actions/checkout@v4	# Reference na existující akci
      - name: Setup Node.js		    # 2: Nainstaluj prostředí (Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies  # 3: Nainstaluj závislosti
        run: |
          cd prototype
          npm install
      - name: Build project		# 5: Vytvoř production bundle
        run: |
          cd prototype
          npm run build
